### PR TITLE
Fe about us page create

### PR DESCRIPTION
**Pull request by MelanyCristy**
*There will be some code reformatted too, blank spaces and such. It looks like a lot of code changed but in reality it is just some formatting (not overwrite) code.
*I added the footer everywhere, not sure if we wouldn’t want it everywhere.
*About the footer, i added some real links for the perflow's social media but more than that i have no idea what else can be added.
*The about us page is really simple right now, has no information but it can be added easily by replacing the "Lorem ipsum" text.

### CODE REVIEW

**Review by jshortz — COMMENTED** [review]
Should we not do 3 PRs here (from 3 different branches) - footer, About Us, and code edits? I'm especially concerned about the code editing, which I think is a great idea, but is likely to generate some merge conflicts. Thoughts?

**Comment by MelanyCristy** [comment]
> Should we not do 3 PRs here (from 3 different branches) - footer, About Us, and code edits? I'm especially concerned about the code editing, which I think is a great idea, but is likely to generate some merge conflicts. Thoughts?

Answering to that, i will say it will (probably) be conflicts no matter what (because this branch it’s getting stuck behind). The editing wasn’t more than just remove the blank spaces, maybe some warnings that the console complaint about but not something big at all, im sure. It can be considered as two tasks since i created the footer and the about us page only. It's not 3 different branches.

**Comment by jshortz** [comment]
I agree footer and about us are two tasks. I would, however, consider refactoring the code as a third and separate task (especially since it involves code unrelated to the footer and about us pages). Hopefully Pratima or someone else can voice an opinion tomorrow.

**Review by pratima-shegokar — DISMISSED** [review]
we need to do 3 PRs here (from 3 different branches) - footer, About Us, and code edits? There is no conflicts but so many changes and so many files in one pull request its not  good .It may affect something which is perfectly fine . also we divided the PBI is in smaller task so we can differentiate the mistake if happend. so please make it 2 request "footer ,about us" is one because that is on functionality and we are adding new code .  but code edits 
definitely need new pull request.

**Comment by MelanyCristy** [comment]
> we need to do 3 PRs here (from 3 different branches) - footer, About Us, and code edits? There is no conflicts but so many changes and so many files in one pull request its not good .It may affect something which is perfectly fine . also we divided the PBI is in smaller task so we can differentiate the mistake if happend. so please make it 2 request "footer ,about us" is one because that is on functionality and we are adding new code . but code edits
> definitely need new pull request.

I think it will be much better if you guys check the files changed and see if it actually creates problems because as i see it it was more formatting code while i was fixing conflicts (not intentionally as a task) but i do understand the concern but at the same time i believe it will be helpful to have more code reformatted for the end of the project will be easier for the person that has that task (reformat all our code). I don't know, my opinion is that, i do understand it is too much files changed and I’m sorry for that i didn’t thought it will be that much but as i said before in reality we do need to have a clean code.

**Review by pratima-shegokar — APPROVED** [review]
font-awesome  library  is used  for icons . check with current changes . no conflicts there also some code changes are there but its necessary.

**Review by MiladYaqo — APPROVED** [review]
Looks good

**Pull request merged**
